name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup environment variables
      run: |
        cp .env.example .env
        export DJANGO_SETTINGS_MODULE=cdc_portal.settings
    - name: Install dependencies
      working-directory: ./backend
      run: |
        sudo apt-get install libpq-dev 
        pip3 install coverage
        pip3 install pipenv
    - name: Linting
      working-directory: ./backend
      run: |
        pipenv install --dev
        source "$(pipenv --venv)"/bin/activate
        flake8 .
    - name: Migrations
      working-directory: ./backend
      run: |
        source "$(pipenv --venv)"/bin/activate
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Coverage
      working-directory: ./backend
      run: |
        source "$(pipenv --venv)"/bin/activate
        pip3 install coverage
        coverage run --source='.' manage.py test
  