name: Deployment CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker
        run: |
          cd production
          cp .env.example .env
          docker-compose build
